#!/usr/bin/env python3
"""
Generates an animated terminal-style GitHub profile card (dark.svg + light.svg).

Everything you'd normally want to tweak lives in CONFIG / ASCII_ART / INFO below.
"""

from html import escape
from pathlib import Path

# ----------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------
PORTRAIT_FILE = "portrait.txt"   # generated by photo_to_ascii.py

def load_portrait():
    f = Path(__file__).parent / PORTRAIT_FILE
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip("\n").split("\n")
    return ["[ portrait.txt missing ]"]


# (label, value, colour-key)  |  colour-key: key / val / accent / warn / muted
INFO = [
    ("__header__", "Naveen Babu", ""),
    ("__rule__", "", ""),
    ("__line__",  "currently making tomorrow's bugs.", "muted"),
    ("__line__",  "eventually turning them into features.", "muted"),
    ("__rule__", "", ""),
    ("Role",     "AI & Software Developer", "val"),
    ("Edu",      "B.Tech CSE (AI), Amrita Vishwa Vidyapeetham (2027)", "val"),
    ("Focus",    "├── Multi-Agent AI Systems", "accent"),
    ("",         "├── AI-Powered Developer Tools", "accent"),
    ("",         "└── Open-Source Projects", "accent"),
    ("__blank__", "", ""),
    ("__cmd__",  "make", ""),
    ("__line__", "[✓] ideas", "key"),
    ("__line__", "[✓] prototypes", "key"),
    ("__line__", "[✓] bugs", "key"),
    ("__line__", "[✓] late-night commits", "key"),
    ("__line__", "[ ] documentation", "muted"),
    ("__blank__", "", ""),
    ("__section__", "~/stack", ""),
    ("Lang",     "Python · JavaScript · TypeScript · Java · C++", "val"),
    ("",         "SQL · MATLAB · C · Rust · Dart · Kotlin", "val"),
    ("",         "Flutter", "val"),
    ("Frontend", "HTML5 · CSS3 · React · Next.js · Tailwind CSS", "val"),
    ("",         "Bootstrap · Flutter · Figma", "val"),
    ("Data",     "PostgreSQL · MongoDB · Firebase · Supabase", "val"),
    ("",         "Neon", "val"),
    ("AI/ML",    "TensorFlow · PyTorch · Scikit-learn · Pandas", "val"),
    ("",         "NumPy · OpenCV", "val"),
    ("Tools",    "Git · GitHub · VS Code · Docker · Arduino", "val"),
    ("__blank__", "", ""),
    ("__cmd__",  "cat roadmap.md", ""),
    ("__line__", "[ ] make something cool", "muted"),
    ("__line__", "[ ] make it useful", "muted"),
    ("__line__", "[ ] make it open source", "muted"),
    ("__line__", "[x] have fun doing it", "key"),
    ("__blank__", "", ""),
    ("__section__", "~/reach", ""),
    ("Web",      "naveenbabu.pages.dev", "accent"),
    ("In",       "linkedin.com/in/naveen-babu-699215224", "accent"),
    ("X",        "x.com/naveenastra", "accent"),
    ("Mail",     "nbknight23@gmail.com", "accent"),
    ("__blank__", "", ""),
    ("__blank__", "", ""),
    ("__line__", "sleep is optional.", "cool"),
    ("__line__", "git push isn't.", "cool"),
]

THEMES = {
    "dark": {
        "bg": "#0d1117", "panel": "#161b22", "border": "#30363d",
        "text": "#c9d1d9", "muted": "#8b949e", "key": "#3fb950",
        "accent": "#58a6ff", "warn": "#d29922", "art": "#bc8cff",
        "prompt": "#3fb950", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
    "light": {
        "bg": "#ffffff", "panel": "#f6f8fa", "border": "#d0d7de",
        "text": "#1f2328", "muted": "#59636e", "key": "#1a7f37",
        "accent": "#0969da", "warn": "#9a6700", "art": "#8250df",
        "prompt": "#1a7f37", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
}

W, H = 980, 825
ART_X, ART_Y = 30, 86
ART_CW = 3.9          # forced char width (textLength keeps this exact in any font)
ART_LH = ART_CW * 1.72
INFO_X, INFO_Y, INFO_LH = 448, 92, 17.5
VAL_X = INFO_X + 92


# ----------------------------------------------------------------------------
# RENDER
# ----------------------------------------------------------------------------
def render(theme_name, colors):
    art_lines = load_portrait()

    parts = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
        f'\'JetBrains Mono\', \'Cascadia Code\', Menlo, Consolas, monospace">'
    )

    # styles + animations
    parts.append(f"""<style>
    .art  {{ fill:{colors['art']}; font-size:6.2px; white-space:pre; }}
    .key  {{ fill:{colors['key']}; font-size:13px; font-weight:700; }}
    .val  {{ fill:{colors['text']}; font-size:13px; }}
    .acc  {{ fill:{colors['accent']}; font-size:13px; }}
    .wrn  {{ fill:{colors['warn']}; font-size:13px; }}
    .mut  {{ fill:{colors['muted']}; font-size:12px; }}
    .hdr  {{ fill:{colors['accent']}; font-size:15px; font-weight:700; }}
    .sec  {{ fill:{colors['muted']}; font-size:12px; letter-spacing:1px; }}
    .ttl  {{ fill:{colors['muted']}; font-size:12px; }}
    .cool {{ fill:{colors['accent']}; font-size:13px; font-style:italic; font-weight:600; }}
    .row  {{ opacity:1; animation: fade .35s ease backwards; }}
    @keyframes fade {{ from {{ opacity:0; transform:translateY(3px); }}
                       to   {{ opacity:1; transform:translateY(0); }} }}
    .cur  {{ fill:{colors['prompt']}; animation: blink 1s steps(1) infinite; }}
    @keyframes blink {{ 50% {{ opacity:0; }} }}
    .artline {{ opacity:1; animation: fade .3s ease backwards; }}
    </style>""")

    # window chrome
    parts.append(
        f'<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" '
        f'fill="{colors["bg"]}" stroke="{colors["border"]}" stroke-width="1.5"/>'
    )
    parts.append(
        f'<path d="M1 13 a12 12 0 0 1 12 -12 h{W-26} a12 12 0 0 1 12 12 v25 h{-(W-2)} z" '
        f'fill="{colors["panel"]}"/>'
    )
    parts.append(f'<line x1="1" y1="38" x2="{W-1}" y2="38" stroke="{colors["border"]}"/>')
    for i, c in enumerate(["dot1", "dot2", "dot3"]):
        parts.append(f'<circle cx="{24 + i*20}" cy="20" r="6" fill="{colors[c]}"/>')

    # ascii art
    for i, line in enumerate(art_lines):
        if not line.strip():
            continue
        y = ART_Y + i * ART_LH
        delay = 0.15 + i * 0.012
        tl = len(line) * ART_CW
        parts.append(
            f'<text x="{ART_X}" y="{y:.1f}" class="art artline" xml:space="preserve" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs" '
            f'style="animation-delay:{delay:.2f}s">{escape(line)}</text>'
        )

    # info block
    y = INFO_Y
    delay = 0.35
    cls_map = {"val": "val", "accent": "acc", "warn": "wrn", "muted": "mut", "key": "key", "cool": "cool"}

    for label, value, ckey in INFO:
        d = f'style="animation-delay:{delay:.2f}s"'
        if label == "__header__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="hdr row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__rule__":
            parts.append(
                f'<line x1="{INFO_X}" y1="{y-8:.1f}" x2="{W-40}" y2="{y-8:.1f}" '
                f'stroke="{colors["border"]}" class="row" {d}/>'
            )
            y += 8
        elif label == "__blank__":
            y += 10
            continue
        elif label == "__section__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="sec row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__cmd__":
            parts.append(
                f'<text x="{INFO_X}" y="{y:.1f}" class="row" {d}>'
                f'<tspan class="key">$</tspan>'
                f'<tspan class="val" dx="8">{escape(value)}</tspan></text>'
            )
            y += INFO_LH
        elif label == "__line__":
            cls = cls_map.get(ckey, "val")
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="{cls} row" {d}>{escape(value)}</text>')
            y += INFO_LH
        else:
            cls = cls_map.get(ckey, "val")
            if label:
                parts.append(
                    f'<text x="{INFO_X}" y="{y:.1f}" class="key row" {d}>{escape(label)}</text>'
                )
            parts.append(
                f'<text x="{VAL_X}" y="{y:.1f}" class="{cls} row" {d}>{escape(value)}</text>'
            )
            y += INFO_LH
        delay += 0.07

    parts.append("</svg>")
    return "\n".join(parts)


def main():
    out = Path(__file__).parent
    for name, colors in THEMES.items():
        (out / f"{name}.svg").write_text(render(name, colors), encoding="utf-8")
        print(f"wrote {name}.svg")


if __name__ == "__main__":
    main()
