#!/usr/bin/env python3
"""
Generates an animated terminal-style GitHub profile card (dark.svg + light.svg).

Everything you'd normally want to tweak lives in CONFIG / ASCII_ART / INFO below.
"""

from html import escape
from pathlib import Path

# ----------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------
PORTRAIT_FILE = "portrait.txt"   # generated by photo_to_ascii.py

def load_portrait():
    f = Path(__file__).parent / PORTRAIT_FILE
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip("\n").split("\n")
    return ["[ portrait.txt missing ]"]


# (label, value, colour-key)  |  colour-key: key / val / accent / warn / muted
INFO = [
    ("__header__", "Naveen Babu", ""),
    ("__rule__", "", ""),
    ("__line__",  "currently making tomorrow's bugs.", "muted"),
    ("__line__",  "eventually turning them into features.", "muted"),
    ("__rule__", "", ""),
    ("Role",     "AI & Software Developer", "val"),
    ("Edu",      "B.Tech CSE (AI), Amrita Vishwa Vidyapeetham (2027)", "val"),
    ("Focus",    "├── Multi-Agent AI Systems", "accent"),
    ("",         "├── AI-Powered Developer Tools", "accent"),
    ("",         "└── Open-Source Projects", "accent"),
    ("__blank__", "", ""),
    ("__cmd__",  "make", ""),
    ("__line__", "[✓] ideas", "key"),
    ("__line__", "[✓] prototypes", "key"),
    ("__line__", "[✓] bugs", "key"),
    ("__line__", "[✓] late-night commits", "key"),
    ("__line__", "[ ] documentation", "muted"),
    ("__blank__", "", ""),
    ("__section__", "~/stack", ""),
    ("Lang",     "Python · JavaScript · TypeScript · Java · C++", "val"),
    ("",         "SQL · MATLAB · C · Rust · Dart · Kotlin", "val"),
    ("",         "Flutter", "val"),
    ("Frontend", "HTML5 · CSS3 · React · Next.js · Tailwind CSS", "val"),
    ("",         "Bootstrap · Flutter · Figma", "val"),
    ("Data",     "PostgreSQL · MongoDB · Firebase · Supabase", "val"),
    ("",         "Neon", "val"),
    ("AI/ML",    "TensorFlow · PyTorch · Scikit-learn · Pandas", "val"),
    ("",         "NumPy · OpenCV", "val"),
    ("Tools",    "Git · GitHub · VS Code · Docker · Arduino", "val"),
    ("__blank__", "", ""),
    ("__cmd__",  "cat roadmap.md", ""),
    ("__line__", "[ ] make something cool", "muted"),
    ("__line__", "[ ] make it useful", "muted"),
    ("__line__", "[ ] make it open source", "muted"),
    ("__line__", "[x] have fun doing it", "key"),
    ("__blank__", "", ""),
    ("__section__", "~/reach", ""),
    ("Web",      "naveenbabu.pages.dev", "accent"),
    ("In",       "linkedin.com/in/naveen-babu-699215224", "accent"),
    ("X",        "x.com/naveenastra", "accent"),
    ("Mail",     "nbknight23@gmail.com", "accent"),
    ("__blank__", "", ""),
    ("__blank__", "", ""),
    ("__blank__", "", ""),
    ("__blank__", "", ""),
    ("__blank__", "", ""),
    ("__line__", "sleep is optional.", "cool"),
    ("__line__", "git push isn't.", "cool"),
]

THEMES = {
    "dark": {
        "bg": "#0d1117", "panel": "#161b22", "border": "#30363d",
        "text": "#c9d1d9", "muted": "#8b949e", "key": "#3fb950",
        "accent": "#58a6ff", "warn": "#d29922", "art": "#bc8cff",
        "prompt": "#3fb950", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
    "light": {
        "bg": "#ffffff", "panel": "#f6f8fa", "border": "#d0d7de",
        "text": "#1f2328", "muted": "#59636e", "key": "#1a7f37",
        "accent": "#0969da", "warn": "#9a6700", "art": "#8250df",
        "prompt": "#1a7f37", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
}

W, H = 980, 860
ART_X, ART_Y = 30, 86
ART_CW = 3.9          # forced char width (textLength keeps this exact in any font)
ART_LH = ART_CW * 1.72
INFO_X, INFO_Y, INFO_LH = 448, 92, 17.5
VAL_X = INFO_X + 92

# typewriter-reveal pacing (info panel: chars "typed" one at a time, like a
# streamed AI response; ascii art: fast overlapping wipe, like it's printing)
CHAR_DUR, MIN_DUR, MAX_DUR, ROW_GAP = 0.004, 0.02, 0.09, 0.006
ART_DUR, ART_GAP = 0.03, 0.003


# ----------------------------------------------------------------------------
# RENDER
# ----------------------------------------------------------------------------
def render(theme_name, colors):
    art_lines = load_portrait()

    parts = []
    defs = []
    clip_n = [0]

    def reveal(x, y, cls_attr, content, char_len, begin, dur, extra=""):
        """Emit a <text> that wipes in left-to-right via an animated clip-path."""
        cid = f"cp{clip_n[0]}"
        clip_n[0] += 1
        steps = max(4, min(int(char_len), 30))
        vals = ";".join(f"{k / steps:.4f}" for k in range(steps + 1))
        defs.append(
            f'<clipPath id="{cid}" clipPathUnits="objectBoundingBox">'
            f'<rect x="0" y="0" width="0" height="1">'
            f'<animate attributeName="width" values="{vals}" calcMode="discrete" '
            f'begin="{begin:.2f}s" dur="{dur:.2f}s" fill="freeze"/>'
            f'</rect></clipPath>'
        )
        parts.append(
            f'<text x="{x}" y="{y:.1f}" {cls_attr} clip-path="url(#{cid})" {extra}>{content}</text>'
        )

    def type_dur(char_len):
        return max(MIN_DUR, min(MAX_DUR, CHAR_DUR * char_len))

    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
        f'\'JetBrains Mono\', \'Cascadia Code\', Menlo, Consolas, monospace">'
    )

    # styles + animations
    parts.append(f"""<style>
    .art  {{ fill:{colors['art']}; font-size:6.2px; white-space:pre; }}
    .key  {{ fill:{colors['key']}; font-size:13px; font-weight:700; }}
    .val  {{ fill:{colors['text']}; font-size:13px; }}
    .acc  {{ fill:{colors['accent']}; font-size:13px; }}
    .wrn  {{ fill:{colors['warn']}; font-size:13px; }}
    .mut  {{ fill:{colors['muted']}; font-size:12px; }}
    .hdr  {{ fill:{colors['accent']}; font-size:15px; font-weight:700; }}
    .sec  {{ fill:{colors['muted']}; font-size:12px; letter-spacing:1px; }}
    .ttl  {{ fill:{colors['muted']}; font-size:12px; }}
    .cool {{ fill:{colors['accent']}; font-size:13px; font-style:italic; font-weight:600; }}
    .rule {{ opacity:1; animation: fade .4s ease backwards; }}
    @keyframes fade {{ from {{ opacity:0; }} to {{ opacity:1; }} }}
    </style>""")

    # window chrome
    parts.append(
        f'<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" '
        f'fill="{colors["bg"]}" stroke="{colors["border"]}" stroke-width="1.5"/>'
    )
    parts.append(
        f'<path d="M1 13 a12 12 0 0 1 12 -12 h{W-26} a12 12 0 0 1 12 12 v25 h{-(W-2)} z" '
        f'fill="{colors["panel"]}"/>'
    )
    parts.append(f'<line x1="1" y1="38" x2="{W-1}" y2="38" stroke="{colors["border"]}"/>')
    for i, c in enumerate(["dot1", "dot2", "dot3"]):
        parts.append(f'<circle cx="{24 + i*20}" cy="20" r="6" fill="{colors[c]}"/>')

    # ascii art — fast cascading wipe, each line overlapping the next
    art_begin = 0.1
    for i, line in enumerate(art_lines):
        if not line.strip():
            continue
        y = ART_Y + i * ART_LH
        tl = len(line) * ART_CW
        reveal(
            ART_X, y, 'class="art"', escape(line), len(line),
            art_begin, ART_DUR,
            extra=f'xml:space="preserve" textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs"',
        )
        art_begin += ART_GAP

    # info block — sequential "typing", one field/line at a time
    y = INFO_Y
    delay = 0.3
    cls_map = {"val": "val", "accent": "acc", "warn": "wrn", "muted": "mut", "key": "key", "cool": "cool"}

    for label, value, ckey in INFO:
        if label == "__header__":
            dur = type_dur(len(value))
            reveal(INFO_X, y, 'class="hdr"', escape(value), len(value), delay, dur)
            delay += dur + ROW_GAP
            y += INFO_LH
        elif label == "__rule__":
            parts.append(
                f'<line x1="{INFO_X}" y1="{y-8:.1f}" x2="{W-40}" y2="{y-8:.1f}" '
                f'stroke="{colors["border"]}" class="rule" style="animation-delay:{delay:.2f}s"/>'
            )
            delay += 0.15
            y += 8
        elif label == "__blank__":
            y += 10
            continue
        elif label == "__section__":
            dur = type_dur(len(value))
            reveal(INFO_X, y, 'class="sec"', escape(value), len(value), delay, dur)
            delay += dur + ROW_GAP
            y += INFO_LH
        elif label == "__cmd__":
            content = f'<tspan class="key">$</tspan><tspan class="val" dx="8">{escape(value)}</tspan>'
            dur = type_dur(len(value) + 2)
            reveal(INFO_X, y, "", content, len(value) + 2, delay, dur)
            delay += dur + ROW_GAP
            y += INFO_LH
        elif label == "__line__":
            cls = cls_map.get(ckey, "val")
            dur = type_dur(len(value))
            reveal(INFO_X, y, f'class="{cls}"', escape(value), len(value), delay, dur)
            delay += dur + ROW_GAP
            y += INFO_LH
        else:
            cls = cls_map.get(ckey, "val")
            if label:
                ldur = type_dur(len(label))
                reveal(INFO_X, y, 'class="key"', escape(label), len(label), delay, ldur)
                delay += ldur + ROW_GAP
            vdur = type_dur(len(value))
            reveal(VAL_X, y, f'class="{cls}"', escape(value), len(value), delay, vdur)
            delay += vdur + ROW_GAP
            y += INFO_LH

    parts.append(f'<defs>{"".join(defs)}</defs>')
    parts.append("</svg>")
    return "\n".join(parts)


def main():
    out = Path(__file__).parent
    for name, colors in THEMES.items():
        (out / f"{name}.svg").write_text(render(name, colors), encoding="utf-8")
        print(f"wrote {name}.svg")


if __name__ == "__main__":
    main()
